### ISSUE TITLE
Mule artifacts

### ISSUE THREAD

**Issue by pkasson** [mule-lint/mule-lint-maven-plugin#2]
Is it possible to get the flow artifacts - name, sub flow, steps, etc, using the Mule Lint library ?  I tried to use it from Maven before I saw this plugin and kaboom.

So, how hard would it be to have a call into the groovy code to return this data ... since you are already capturing it for your analysis ?

Thanks

**Comment by cgorshing** [comment]
Closing as conversation is tracked at https://github.com/Nuisto/mule-lint/issues/11

**Comment by pkasson** [comment]
I want to perform analysis across several projects - catalog artifacts - what flows / sub flows / components. One reason is to find violations - naming standards, etc. Look for things like 'somewhere we had a routine that did ...'. So need to get not just high level (flow name, step name) but the attributes therein. Can also be used for documenting.
