### ISSUE TITLE
MojoExecutionException- Issue while building mule-lint-maven-plugin 

### ISSUE THREAD

**Issue by djangir10** [mule-lint/mule-lint-maven-plugin#6]
Hi @cgorshing

Using mvn clean install I am getting below error while building mule-lint-maven-plugin

Check the screenshots and error below :

https://drive.google.com/folderview?id=111J1knb0utpqwnzvfHgWgg-L1E-roItG

Multiple markers at this line

          - org.nuisto.MuleLint cannot be resolved to a type

          - Type safety: The method toArray(Object[]) belongs to the raw type List. References to generic type List<E> should be

           parameterized

          - org.nuisto.MuleLint cannot be resolved to a type

Steps which I am following:

Building mule-lint using mvn clean install ---- no issues
Then building mule-lint-maven-plugin using mvn clean install command ---- getting above error

Let me know if I am doing anything wrong here.

**Comment by cgorshing** [comment]
Closing this for now as we discussed in another issue.
